name = "backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# [vars]
# MY_VARIABLE = "production_value"

[[d1_databases]]
binding = "DB"
database_name = "network-monitor-db"
database_id = "cb14f778-1b19-46d3-8b71-cead5360091f"
